from __future__ import annotations

import argparse
from pathlib import Path

import yaml

import bootstrap  # noqa: F401

from ggml_hrx_kernel_bench.import_support_surface import validated_import_ops


def _safe_name(value: str) -> str:
    return ''.join(ch if ch.isalnum() or ch in ('-', '_') else '_' for ch in value)


def _cmake_quote(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _load_supported_grouped_yaml_ops(yaml_path: Path) -> list[str]:
    payload = yaml.safe_load(yaml_path.read_text(encoding='utf-8'))
    if not isinstance(payload, dict):
        raise RuntimeError('grouped YAML must be a top-level object')
    ops = payload.get('ops')
    if not isinstance(ops, dict):
        raise RuntimeError('grouped YAML must contain an ops mapping')
    supported_ops = validated_import_ops()
    result = [
        op_name
        for op_name in sorted(ops)
        if isinstance(op_name, str) and op_name and op_name.upper() in supported_ops
    ]
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description='Generate a CMake include that registers per-op kernel runtime tests.')
    parser.add_argument('--output', required=True)
    parser.add_argument('--name', required=True)
    parser.add_argument('--grouped-yaml', required=True)
    parser.add_argument('--generated-import-dir', required=True)
    parser.add_argument('--python-executable', required=True)
    parser.add_argument('--runner-script', required=True)
    parser.add_argument('--runtime-output-dir', required=True)
    parser.add_argument('--case-selector', default='0')
    parser.add_argument('--tool-dir')
    parser.add_argument('--rocm-path')
    args = parser.parse_args()

    output_path = Path(args.output).resolve()
    grouped_yaml_path = Path(args.grouped_yaml).resolve()
    generated_import_dir = Path(args.generated_import_dir).resolve()
    runtime_output_dir = Path(args.runtime_output_dir).resolve()

    lines = ['# Generated by generate_kernel_runtime_tests_cmake.py', '']
    for op_name in _load_supported_grouped_yaml_ops(grouped_yaml_path):
        op_safe_name = _safe_name(op_name)
        manifest_path = generated_import_dir / 'ops' / op_safe_name / 'generated-kernel-tests.json'
        op_output_dir = runtime_output_dir / op_safe_name
        command_parts = [
            _cmake_quote(args.python_executable),
            _cmake_quote(str(Path(args.runner_script).resolve())),
            _cmake_quote(str(manifest_path)),
            '--case-selector',
            _cmake_quote(args.case_selector),
            '--output-dir',
            _cmake_quote(str(op_output_dir)),
        ]
        if args.tool_dir:
            command_parts.extend(['--tool-dir', _cmake_quote(str(Path(args.tool_dir).resolve()))])
        if args.rocm_path:
            command_parts.extend(['--rocm-path', _cmake_quote(str(Path(args.rocm_path).resolve()))])
        lines.extend([
            'add_test(',
            f'  NAME kernel-run-{args.name}-{op_safe_name}-generated',
            '  COMMAND',
            '    ' + ' '.join(command_parts),
            ')',
            f'set_tests_properties(kernel-run-{args.name}-{op_safe_name}-generated PROPERTIES SKIP_RETURN_CODE 125)',
            '',
        ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text('\n'.join(lines), encoding='utf-8')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
