from __future__ import annotations

import argparse
from pathlib import Path

import yaml

import bootstrap  # noqa: F401

from ggml_hrx_kernel_bench.import_support_surface import validated_import_ops


def _safe_name(value: str) -> str:
    return ''.join(ch if ch.isalnum() or ch in ('-', '_') else '_' for ch in value)


def _cmake_quote(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _load_grouped_yaml_ops(yaml_path: Path, *, all_ops: bool) -> list[str]:
    payload = yaml.safe_load(yaml_path.read_text(encoding='utf-8'))
    if not isinstance(payload, dict):
        raise RuntimeError('grouped YAML must be a top-level object')
    ops = payload.get('ops')
    if not isinstance(ops, dict):
        raise RuntimeError('grouped YAML must contain an ops mapping')
    if all_ops:
        return [
            op_name
            for op_name in sorted(ops)
            if isinstance(op_name, str) and op_name
        ]
    supported_ops = validated_import_ops()
    return [
        op_name
        for op_name in sorted(ops)
        if isinstance(op_name, str) and op_name and op_name.upper() in supported_ops
    ]


def _append_optional_path(parts: list[str], flag: str, value: str | None) -> None:
    if value:
        parts.extend([flag, _cmake_quote(str(Path(value).resolve()))])


def _append_optional_text(parts: list[str], flag: str, value: str | None) -> None:
    if value:
        parts.extend([flag, _cmake_quote(value)])


def _add_test(lines: list[str], *, name: str, command_parts: list[str]) -> None:
    lines.extend(
        [
            'add_test(',
            f'  NAME {name}',
            '  COMMAND',
            '    ' + ' '.join(command_parts),
            ')',
            '',
        ]
    )


def _set_properties(lines: list[str], *, name: str, properties: list[tuple[str, str]]) -> None:
    if not properties:
        return
    lines.extend(
        [
            'set_tests_properties(',
            f'  {name}',
            '  PROPERTIES',
        ]
    )
    for key, value in properties:
        lines.append(f'    {key} {value}')
    lines.extend([')', ''])


def _add_prepare_build_command(
    lines: list[str],
    *,
    descriptor_manifest_path: Path,
    run_manifest_path: Path,
    generate_command: list[str],
    prepare_command: list[str],
    dependencies: list[str],
) -> None:
    lines.extend(
        [
            'add_custom_command(',
            '  OUTPUT',
            f'    {_cmake_quote(str(descriptor_manifest_path))}',
            f'    {_cmake_quote(str(run_manifest_path))}',
            '  COMMAND',
            '    ' + ' '.join(generate_command),
            '  COMMAND',
            '    ' + ' '.join(prepare_command),
        ]
    )
    if dependencies:
        lines.append('  DEPENDS')
        for dependency in dependencies:
            lines.append(f'    {_cmake_quote(dependency)}')
    lines.extend(['  VERBATIM', ')', ''])


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Generate a CMake include that registers per-op Loom descriptor tests.'
    )
    parser.add_argument('--output', required=True)
    parser.add_argument('--name', required=True)
    parser.add_argument('--grouped-yaml', required=True)
    parser.add_argument('--generated-import-dir', required=True)
    parser.add_argument('--python-executable', required=True)
    parser.add_argument('--descriptor-generator-script', required=True)
    parser.add_argument('--descriptor-runner-script', required=True)
    parser.add_argument('--descriptor-output-dir', required=True)
    parser.add_argument('--prepare-output-dir', required=True)
    parser.add_argument('--execute-output-dir')
    parser.add_argument('--kernel-dir')
    parser.add_argument('--routing-dir')
    parser.add_argument('--target', default='gfx1100')
    parser.add_argument('--max-elements', default='65536')
    parser.add_argument('--limit')
    parser.add_argument('--runner', default='ggml-hrx-run-loom-simple')
    parser.add_argument('--tool-dir')
    parser.add_argument('--repo-root')
    parser.add_argument('--build-prepare-target')
    parser.add_argument('--import-target')
    parser.add_argument('--exclude-op', action='append', default=[])
    parser.add_argument('--all-ops', action='store_true')
    parser.add_argument('--execute-hsa', action='store_true')
    args = parser.parse_args()

    output_path = Path(args.output).resolve()
    grouped_yaml_path = Path(args.grouped_yaml).resolve()
    generated_import_dir = Path(args.generated_import_dir).resolve()
    descriptor_output_dir = Path(args.descriptor_output_dir).resolve()
    prepare_output_dir = Path(args.prepare_output_dir).resolve()
    execute_output_dir = Path(args.execute_output_dir).resolve() if args.execute_output_dir else None

    lines = ['# Generated by generate_loom_descriptor_tests_cmake.py', '']
    build_prepare_outputs: list[Path] = []
    build_prepare_target = args.build_prepare_target
    import_target = args.import_target
    excluded_ops = {str(op_name).upper() for op_name in args.exclude_op}
    for op_name in _load_grouped_yaml_ops(grouped_yaml_path, all_ops=args.all_ops):
        if op_name.upper() in excluded_ops:
            continue
        op_safe_name = _safe_name(op_name)
        fixture_name = f'descriptor-{args.name}-{op_safe_name}'
        manifest_path = generated_import_dir / 'ops' / op_safe_name / 'generated-kernel-tests.json'
        op_descriptor_output_dir = descriptor_output_dir / op_safe_name
        descriptor_manifest_path = op_descriptor_output_dir / 'loom-execution-descriptors.json'
        op_prepare_output_dir = prepare_output_dir / op_safe_name
        prepare_run_manifest_path = op_prepare_output_dir / 'loom-execution-runs.json'

        generate_name = f'kernel-descriptor-generate-{args.name}-{op_safe_name}-generated'
        generate_command = [
            _cmake_quote(args.python_executable),
            _cmake_quote(str(Path(args.descriptor_generator_script).resolve())),
            _cmake_quote(str(manifest_path)),
            '--output-dir',
            _cmake_quote(str(op_descriptor_output_dir)),
            '--target',
            _cmake_quote(args.target),
            '--max-elements',
            _cmake_quote(str(args.max_elements)),
        ]
        _append_optional_path(generate_command, '--kernel-dir', args.kernel_dir)
        _append_optional_path(generate_command, '--routing-dir', args.routing_dir)
        _append_optional_text(generate_command, '--limit', args.limit)
        _add_test(lines, name=generate_name, command_parts=generate_command)
        _set_properties(
            lines,
            name=generate_name,
            properties=[('FIXTURES_SETUP', fixture_name)],
        )

        prepare_command = [
            _cmake_quote(args.python_executable),
            _cmake_quote(str(Path(args.descriptor_runner_script).resolve())),
            _cmake_quote(str(descriptor_manifest_path)),
            '--output-dir',
            _cmake_quote(str(op_prepare_output_dir)),
            '--runner',
            _cmake_quote(args.runner),
        ]
        _append_optional_path(prepare_command, '--repo-root', args.repo_root)
        _append_optional_text(prepare_command, '--tool-dir', args.tool_dir)
        _append_optional_text(prepare_command, '--limit', args.limit)
        if build_prepare_target:
            build_generate_command = [*generate_command, '--quiet']
            build_prepare_command = [*prepare_command, '--quiet']
            build_prepare_dependencies = [
                str(manifest_path),
                str(Path(args.descriptor_generator_script).resolve()),
                str(Path(args.descriptor_runner_script).resolve()),
            ]
            _add_prepare_build_command(
                lines,
                descriptor_manifest_path=descriptor_manifest_path,
                run_manifest_path=prepare_run_manifest_path,
                generate_command=build_generate_command,
                prepare_command=build_prepare_command,
                dependencies=build_prepare_dependencies,
            )
            build_prepare_outputs.append(prepare_run_manifest_path)

        if args.execute_hsa:
            execute_name = f'kernel-descriptor-execute-{args.name}-{op_safe_name}-generated'
            op_execute_output_dir = (execute_output_dir or prepare_output_dir / 'execute') / op_safe_name
            execute_command = [
                _cmake_quote(args.python_executable),
                _cmake_quote(str(Path(args.descriptor_runner_script).resolve())),
                _cmake_quote(str(descriptor_manifest_path)),
                '--output-dir',
                _cmake_quote(str(op_execute_output_dir)),
                '--runner',
                _cmake_quote(args.runner),
                '--execute',
                '--progress',
                '--quiet',
            ]
            _append_optional_path(execute_command, '--repo-root', args.repo_root)
            _append_optional_text(execute_command, '--tool-dir', args.tool_dir)
            _append_optional_text(execute_command, '--limit', args.limit)
            _add_test(lines, name=execute_name, command_parts=execute_command)
            _set_properties(
                lines,
                name=execute_name,
                properties=[
                    ('FIXTURES_REQUIRED', fixture_name),
                    ('LABELS', '"hsa;runtime;loom-descriptor"'),
                ],
            )

    if build_prepare_target:
        lines.extend(
            [
                f'add_custom_target({build_prepare_target} ALL',
                '  DEPENDS',
            ]
        )
        for output in build_prepare_outputs:
            lines.append(f'    {_cmake_quote(str(output))}')
        lines.extend([')', ''])
        if import_target:
            lines.extend(
                [
                    f'if(TARGET {import_target})',
                    f'  add_dependencies({build_prepare_target} {import_target})',
                    'endif()',
                    '',
                ]
            )
        lines.extend(
            [
                'if(TARGET ggml-hrx-run-loom-simple)',
                f'  add_dependencies({build_prepare_target} ggml-hrx-run-loom-simple)',
                'endif()',
                '',
            ]
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text('\n'.join(lines), encoding='utf-8')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
