from __future__ import annotations

import argparse
import json
from pathlib import Path


def _safe_name(value: str) -> str:
    return ''.join(ch if ch.isalnum() or ch in ('-', '_') else '_' for ch in value)


def _cmake_quote(value: str) -> str:
    return '"' + value.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _load_ops(expected_coverage_path: Path) -> list[str]:
    payload = json.loads(expected_coverage_path.read_text(encoding='utf-8'))
    operations = payload.get('operations', [])
    if not isinstance(operations, list):
        raise RuntimeError('expected coverage operations must be a list')
    result: list[str] = []
    for index, row in enumerate(operations):
        if not isinstance(row, dict):
            raise RuntimeError(f'operations[{index}] must be an object')
        op_name = row.get('op')
        pass_case_count = row.get('pass_case_count', 0)
        if not isinstance(op_name, str) or not op_name:
            raise RuntimeError(f'operations[{index}].op must be a non-empty string')
        if int(pass_case_count) > 0:
            result.append(op_name)
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description='Generate a CMake include that registers per-op kernel runtime tests.')
    parser.add_argument('--output', required=True)
    parser.add_argument('--name', required=True)
    parser.add_argument('--expected-coverage', required=True)
    parser.add_argument('--generated-import-dir', required=True)
    parser.add_argument('--python-executable', required=True)
    parser.add_argument('--runner-script', required=True)
    parser.add_argument('--runtime-output-dir', required=True)
    parser.add_argument('--case-selector', default='0')
    parser.add_argument('--tool-dir')
    parser.add_argument('--rocm-path')
    args = parser.parse_args()

    output_path = Path(args.output).resolve()
    expected_coverage_path = Path(args.expected_coverage).resolve()
    generated_import_dir = Path(args.generated_import_dir).resolve()
    runtime_output_dir = Path(args.runtime_output_dir).resolve()

    lines = ['# Generated by generate_kernel_runtime_tests_cmake.py', '']
    for op_name in _load_ops(expected_coverage_path):
        op_safe_name = _safe_name(op_name)
        manifest_path = generated_import_dir / 'ops' / op_safe_name / 'generated-kernel-tests.json'
        op_output_dir = runtime_output_dir / op_safe_name
        command_parts = [
            _cmake_quote(args.python_executable),
            _cmake_quote(str(Path(args.runner_script).resolve())),
            _cmake_quote(str(manifest_path)),
            '--case-selector',
            _cmake_quote(args.case_selector),
            '--output-dir',
            _cmake_quote(str(op_output_dir)),
        ]
        if args.tool_dir:
            command_parts.extend(['--tool-dir', _cmake_quote(str(Path(args.tool_dir).resolve()))])
        if args.rocm_path:
            command_parts.extend(['--rocm-path', _cmake_quote(str(Path(args.rocm_path).resolve()))])
        lines.extend([
            'add_test(',
            f'  NAME kernel-run-{args.name}-{op_safe_name}-generated',
            '  COMMAND',
            '    ' + ' '.join(command_parts),
            ')',
            f'set_tests_properties(kernel-run-{args.name}-{op_safe_name}-generated PROPERTIES SKIP_RETURN_CODE 125)',
            '',
        ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text('\n'.join(lines), encoding='utf-8')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
