from __future__ import annotations


VALIDATED_IMPORT_OPS = frozenset(
    {
        "ABS",
        "ADD",
        "ARGSORT",
        "CEIL",
        "CLAMP",
        "CONT",
        "COS",
        "CPY",
        "DIV",
        "ELU",
        "EXP",
        "EXPM1",
        "FLASH_ATTN_EXT",
        "FLOOR",
        "GELU",
        "GELU_ERF",
        "GELU_QUICK",
        "GET_ROWS",
        "HARDSIGMOID",
        "HARDSWISH",
        "LEAKY_RELU",
        "LOG",
        "MUL",
        "MUL_MAT",
        "NEG",
        "ROPE",
        "ROPE_SCALE",
        "ROPE_SET_ROWS",
        "ROUND",
        "RMS_NORM",
        "RELU",
        "SCALE",
        "SET_ROWS",
        "SGN",
        "SIGMOID",
        "SILU",
        "SIN",
        "SOFTCAP",
        "SOFT_MAX",
        "SOFTPLUS",
        "SQR",
        "SQRT",
        "STEP",
        "SUB",
        "SWIGLU",
        "SUM_ROWS",
        "TANH",
        "TRUNC",
        "XIELU",
    }
)


def validated_import_ops() -> frozenset[str]:
    return VALIDATED_IMPORT_OPS
